import { Note } from '../types';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from "docx";

// --- Helper Functions ---

const saveBlob = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const element = document.createElement("a");
    element.href = url;
    element.download = filename;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    URL.revokeObjectURL(url);
};

// Cleans text of internal markers like [PAUSE] before export
const cleanTextForExport = (text: string): string => {
    return text
        .replace(/\[PAUSE\]/gi, '')  // Remove [PAUSE] case insensitive
        .replace(/\(pause\)/gi, '')  // Remove (pause) case insensitive
        .replace(/\[.*?\]/g, (match) => {
            // Keep specific brackets if needed, but remove instruction-like ones
            if (match.toLowerCase().includes('reading') || match.toLowerCase().includes('explanation')) return match;
            return '';
        }) 
        .trim();
};

// Parses markdown-like text (bold/italics) into Docx TextRuns
const parseTextToRuns = (text: string): TextRun[] => {
    // First clean the text
    const cleanedText = cleanTextForExport(text);
    const parts = cleanedText.split(/(\*\*.*?\*\*|\*.*?\*)/g);
    
    return parts.map(part => {
        let content = part;
        let bold = false;
        let italics = false;

        if (part.startsWith('**') && part.endsWith('**')) {
            bold = true;
            content = part.slice(2, -2);
        } else if (part.startsWith('*') && part.endsWith('*')) {
            italics = true;
            content = part.slice(1, -1);
        }

        return new TextRun({
            text: content,
            bold: bold,
            italics: italics
        });
    });
};

const contentToParagraphs = (content: string): Paragraph[] => {
    const lines = content.split('\n');
    return lines.map(line => {
        if (!line.trim()) return new Paragraph({ text: "" }); // Empty line
        return new Paragraph({
            children: parseTextToRuns(line)
        });
    });
};

export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(cleanTextForExport(text));
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
};

// --- Docx Export Functions ---

export const exportChatToDoc = async (note: Note) => {
    const children: any[] = [];

    children.push(new Paragraph({
        text: note.title || "Untitled Note",
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
        spacing: { after: 300 }
    }));

    note.messages.forEach(msg => {
        const roleName = msg.role === 'model' ? 'AI Teacher' : 'You';
        const color = msg.role === 'model' ? "2E7D32" : "1565C0"; 

        children.push(new Paragraph({
            children: [
                new TextRun({
                    text: roleName,
                    bold: true,
                    color: color,
                    size: 24 
                }),
                new TextRun({
                    text: `  [${new Date(msg.timestamp).toLocaleTimeString()}]`,
                    size: 16, 
                    color: "888888"
                })
            ],
            spacing: { before: 200, after: 100 }
        }));

        children.push(...contentToParagraphs(msg.content));
        
        children.push(new Paragraph({
            text: "",
            border: { bottom: { color: "E0E0E0", space: 1, style: BorderStyle.SINGLE, size: 6 } },
            spacing: { after: 200 }
        }));
    });

    const doc = new Document({
        sections: [{
            properties: {},
            children: children
        }]
    });

    const blob = await Packer.toBlob(doc);
    saveBlob(blob, `${note.title.replace(/\s+/g, '_')}_Chat.docx`);
};

export const exportMessageToDoc = async (content: string) => {
    const children = contentToParagraphs(content);
    
    const doc = new Document({
        sections: [{
            properties: {},
            children: [
                new Paragraph({
                    text: "AI Teacher Response",
                    heading: HeadingLevel.HEADING_2,
                    spacing: { after: 200 }
                }),
                ...children,
                new Paragraph({
                    text: "Generated by AI Teacher",
                    spacing: { before: 400 },
                    children: [new TextRun({ italics: true, color: "888888", size: 16 })]
                })
            ]
        }]
    });

    const blob = await Packer.toBlob(doc);
    saveBlob(blob, `AI_Response_${Date.now()}.docx`);
};

// --- Print / PDF Export Functions ---

interface PrintData {
    title: string;
    items: {
        role?: string;
        content: string;
        timestamp?: number;
    }[];
}

const generatePrintHtml = () => {
    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>Document</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
        <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

        <style>
            /* System fonts for mobile-native feel */
            body { 
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                padding: 40px; 
                max-width: 800px; 
                margin: 0 auto; 
                line-height: 1.6; 
                color: #1f2937;
            }

            h1 { 
                color: #059669; 
                border-bottom: 2px solid #059669; 
                padding-bottom: 10px; 
                margin-bottom: 20px;
                page-break-after: auto; 
            }
            .meta { 
                color: #6b7280; 
                font-size: 0.9em; 
                margin-bottom: 30px; 
                page-break-after: auto; 
            }
            
            .msg { 
                margin-bottom: 25px; 
                page-break-inside: auto; 
                break-inside: auto;
                display: block;
            }
            
            .role { 
                font-weight: bold; 
                margin-bottom: 5px; 
                font-size: 0.9em; 
                text-transform: uppercase; 
                page-break-after: avoid; 
                color: #059669;
            }
            .role.user { color: #2563EB; }
            
            .content { 
                font-size: 14px; 
                page-break-inside: auto;
                display: block;
            }
            .content p { margin-bottom: 0.8em; }
            
            /* Print Specifics */
            @media print {
                body { padding: 0; max-width: 100%; }
                #loading-overlay { display: none !important; }
                .msg { page-break-inside: auto; }
                h1 { page-break-before: auto; }
            }
        </style>
      </head>
      <body>
        <div id="loading-overlay" style="text-align: center; margin-top: 50px; color: #666;">
            <h1>Preparing Document...</h1>
            <p>Rendering formatted text and equations.</p>
        </div>

        <h1 id="doc-title" style="display:none"></h1>
        <div class="meta" id="doc-meta" style="display:none"></div>
        <div id="container"></div>

        <script>
            const data = window.PRINT_DATA;
            let attempts = 0;

            function cleanText(text) {
                return text
                    .replace(/\\[PAUSE\\]/gi, '')
                    .replace(/\\(pause\\)/gi, '')
                    .replace(/\\[.*?\\]/g, (match) => {
                        if (match.toLowerCase().includes('reading') || match.toLowerCase().includes('explanation')) return match;
                        return '';
                    });
            }

            function renderContent(markdown) {
                const cleaned = cleanText(markdown);
                // Use marked if available, otherwise simple fallback
                if (typeof marked !== 'undefined') {
                    // Protect Math
                    const mathSegments = [];
                    let pIdx = 0;
                    const protected = cleaned.replace(/(\\$\\$[\\s\\S]*?\\$\\$)|(\\$[^$\\n]*?\\$)/g, (m) => {
                        const pid = 'MATH_' + (pIdx++);
                        mathSegments.push({id: pid, text: m});
                        return pid;
                    });
                    
                    let html = marked.parse(protected);
                    
                    mathSegments.forEach(seg => {
                        html = html.replace(seg.id, seg.text);
                    });
                    return html;
                }
                // Fallback
                return cleaned
                    .replace(/\\*\\*(.*?)\\*\\*/g, '<b>$1</b>')
                    .replace(/\\n/g, '<br>');
            }

            function startRendering() {
                if (!data) return;

                document.getElementById('loading-overlay').style.display = 'none';
                document.getElementById('doc-title').innerText = data.title;
                document.getElementById('doc-title').style.display = 'block';
                document.getElementById('doc-meta').innerText = new Date().toLocaleDateString();
                document.getElementById('doc-meta').style.display = 'block';

                const container = document.getElementById('container');
                
                data.items.forEach(item => {
                    const msgDiv = document.createElement('div');
                    msgDiv.className = 'msg';
                    
                    if (item.role) {
                        const roleDiv = document.createElement('div');
                        roleDiv.className = 'role ' + item.role;
                        const roleName = item.role === 'model' ? 'AI Teacher' : 'You';
                        roleDiv.innerHTML = '<span>' + roleName + '</span>';
                        msgDiv.appendChild(roleDiv);
                    }

                    const contentDiv = document.createElement('div');
                    contentDiv.className = 'content';
                    contentDiv.innerHTML = renderContent(item.content);
                    msgDiv.appendChild(contentDiv);
                    container.appendChild(msgDiv);
                });

                // Render Math if KaTeX loaded
                if (typeof renderMathInElement !== 'undefined') {
                    try {
                        renderMathInElement(document.body, {
                            delimiters: [
                                {left: '$$', right: '$$', display: true},
                                {left: '$', right: '$', display: false}
                            ],
                            throwOnError: false
                        });
                    } catch(e) { console.error(e); }
                }

                setTimeout(() => { window.print(); }, 500);
            }

            function checkLibraries() {
                // Wait for Marked and KaTeX
                if (typeof marked !== 'undefined' && typeof renderMathInElement !== 'undefined') {
                    startRendering();
                } else {
                    attempts++;
                    if (attempts > 20) { // Wait max 2 seconds
                        console.warn("Libraries timed out, printing raw text");
                        startRendering(); 
                    } else {
                        setTimeout(checkLibraries, 100);
                    }
                }
            }

            window.onload = checkLibraries;
        </script>
      </body>
      </html>
    `;
};

const openPrintWindow = (html: string, data: PrintData) => {
    const printWindow = window.open('', '_blank', 'width=900,height=800');
    if (printWindow) {
        (printWindow as any).PRINT_DATA = data;
        printWindow.document.open();
        printWindow.document.write(html);
        printWindow.document.close();
    } else {
        alert("Pop-up blocked. Please allow pop-ups for printing.");
    }
};

export const printChat = (note: Note) => {
    const data: PrintData = {
        title: note.title,
        items: note.messages.map(m => ({
            role: m.role,
            content: m.content,
            timestamp: m.timestamp
        }))
    };
    openPrintWindow(generatePrintHtml(), data);
};

export const printMessage = (content: string) => {
    const data: PrintData = {
        title: "AI Teacher Response",
        items: [{ content: content }]
    };
    openPrintWindow(generatePrintHtml(), data);
};